# Generated by Django 5.2.1 on 2025-11-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff')], default='administrator', max_length=20),
        ),
    ]
