# Generated by Django 5.2.1 on 2025-11-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoiceDate',
        ),
    ]
