# Generated by Django 5.2.7 on 2025-12-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='costPrice',
        ),
        migrations.AddField(
            model_name='product',
            name='costPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
