# Generated by Django 5.2.7 on 2025-12-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_inventory_costprice_product_costprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
    ]
