# Generated by Django 5.2.7 on 2025-12-11 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_category_description_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='qrReference',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customerName',
            field=models.CharField(default='Guest', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customerPhone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='api.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrCodeImage', models.CharField(blank=True, max_length=500, null=True)),
                ('businessName', models.CharField(blank=True, max_length=255, null=True)),
                ('businessAddress', models.TextField(blank=True, null=True)),
                ('businessPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
