# Generated by Django 5.2.1 on 2025-12-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_userprofile_id_userprofile_businessemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paidAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
