# Generated by Django 5.2.7 on 2025-12-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_invoice_paidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='khqrCodeString',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='khqrDeeplink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='khqrLastCheckedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='khqrMd5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='khqrPaymentData',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='khqrShortHash',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='khqrTransactionHash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymentMethod',
            field=models.CharField(choices=[('Cash', 'Cash'), ('KHQR', 'KHQR')], max_length=20),
        ),
    ]
